var defaultTeams = [{
    "name": "Bayern München",
    "logo": "50037",
    "selected": "selected",
    "short-name": "",
},
{
    "name": "Borussia Dortmund",
    "logo": "52758",
    "selected": "selected",
    "short-name": "",
},
{
    "name": "Manchester United",
    "logo": "52682",
    "selected": "selected",
    "short-name": "",
},
{
    "name": "Manchester City",
    "logo": "52919",
    "selected": "selected",
    "short-name": "",
},
{
    "name": "Liverpool",
    "logo": "7889",
    "selected": "selected",
    "short-name": "",
},
{
    "name": "Tottenham Spurs",
    "logo": "1652",
    "selected": "selected",
    "short-name": "",
},
{
    "name": "Chelsea",
    "logo": "52914",
    "selected": "selected",
    "short-name": "",
},
{
    "name": "Arsenal",
    "logo": "52280",
    "selected": "selected",
    "short-name": "",
},
{
    "name": "Paris Saint Germain",
    "logo": "52747",
    "selected": "selected",
    "short-name": "",
},
{
    "name": "Juventus",
    "logo": "50139",
    "selected": "selected",
    "short-name": "",
},
{
    "name": "AC Milan",
    "logo": "50058",
    "selected": "selected",
    "short-name": "",
},
{
    "name": "AS Roma",
    "logo": "50137",
    "selected": "selected",
    "short-name": "",
},
{
    "name": "Real Madrid",
    "logo": "50051",
    "selected": "selected",
    "short-name": "",
},
{
    "name": "FC Barcelona",
    "logo": "50080",
    "selected": "selected",
    "short-name": "",
},
{
    "name": "Atletico Madrid",
    "logo": "50124",
    "selected": "selected",
    "short-name": "",
},

//NOT SELECTED 
{
    "name": "Borussia Mönchengladbach",
    "logo": "52757",
    "selected": false,
    "short-name": "",
},
{
    "name": "Bayer Leverkusen",
    "logo": "50109",
    "selected": false,
    "short-name": "",
},
{
    "name": "VFL Wolfsburg",
    "logo": "64332",
    "selected": false,
    "short-name": "",
},
{
    "name": "FC Schalke 04",
    "logo": "57388",
    "selected": false,
    "short-name": "",
},
{
    "name": "AS Monaco",
    "logo": "50023",
    "selected": false,
    "short-name": "",
},
{
    "name": "Olympique Lyon",
    "logo": "5312",
    "selected": false,
    "short-name": "",
},
{
    "name": "Olympique Marseille",
    "logo": "52748",
    "selected": false,
    "short-name": "",
},
{
    "name": "Ajax",
    "logo": "50143",
    "selected": false,
    "short-name": "",
},
{
    "name": "PSV Eindhoven",
    "logo": "50062",
    "selected": false,
    "short-name": "",
},
{
    "name": "Feyenoord Rotterdam",
    "logo": "52749",
    "selected": false,
    "short-name": "",
},
{
    "name": "Inter Milano",
    "logo": "50138",
    "selected": false,
    "short-name": "",
},
{
    "name": "SSC Napoli",
    "logo": "50136",
    "selected": false,
    "short-name": "",
},
{
    "name": "Lazio",
    "logo": "52973",
    "selected": false,
    "short-name": "",
},
{
    "name": "Beşiktaş",
    "logo": "50157",
    "selected": false,
    "short-name": "",
},
{
    "name": "Galatasaray",
    "logo": "50067",
    "selected": false,
    "short-name": "",
},
{
    "name": "Fenerbahçe",
    "logo": "52692",
    "selected": false,
    "short-name": "",
},
{
    "name": "FC Sevilla",
    "logo": "52714",
    "selected": false,
    "short-name": "",
},
{
    "name": "FC Villarreal",
    "logo": "70691",
    "selected": false,
    "short-name": "",
},
{
    "name": "FC Valencia",
    "logo": "52268",
    "selected": false,
    "short-name": "",
},
{
    "name": "CSKA Moskva",
    "logo": "54266",
    "selected": false,
    "short-name": "",
},
{
    "name": "Zenit",
    "logo": "52826",
    "selected": false,
    "short-name": "",
},
{
    "name": "Celtic Glasgow",
    "logo": "50050",
    "selected": false,
    "short-name": "",
},
{
    "name": "Shakhtar Donetsk",
    "logo": "52707",
    "selected": false,
    "short-name": "",
},

];